import type { Resources } from "./resources";

export const RULES = {
  capacity: { food: 200, debris: 1800, special: 3 } satisfies Resources,
  mapRadius: 3,
  initialExplorationRadius: 1,
  maxExplorationRadius: 3,
  upgradePrices: { 1: 50, 2: 100 } as Record<number, number>,
  dronePrice: 50,
  repairPrice: 30,
  debrisTileChance: 0.75,
  debrisMin: 20,
  debrisMax: 75,
  debrisPriorityMultiplier: 4,
  urgentDebrisPriorityMultiplier: 6,
  specialPairCount: 5,
  firstSpecialPriorityValue: 80,
  mineActionCost: 1,
  fuelCapacity: 100,
  fuelPerStep: 2,
  droneFuelPerHex: 1,
  minePlacementFuel: 4,
  mineScanFuel: 2,
  mineNeutralizeFuel: 2,
  mineArmingDuration: 800,
  mineScanRadius: 2,
  mineMemoryDurations: [10000, 20000, 40000],
  mineMemoryUpgradePrices: { 1: 50, 2: 100 } as Record<number, number>,
  dangerDamage: 15,
  mineDamage: 40,
  cloudDamage: 45,
  cloudExplorationInterval: 6,
  cloudMoveDuration: 2400,
  cloudLifetime: 10000,
  cloudFadeDuration: 800,
  repairThreshold: 45,
  impairedVisionThreshold: 50,
  slowMovementThreshold: 70,
  repairCooldown: 40000,
  riskyResourceThreshold: 200,
  fuelReserve: 3,
  fuelUrgencyThreshold: 20,
  stepDuration: 400,
  fuelServiceStepMultiplier: 3,
  scanDuration: 800,
  collectDuration: 1000,
  serviceDuration: 1200,
  purchaseDuration: 1000,
  rescueDuration: 5000,
  maxLogEntries: 120,
} as const;
